### ISSUE TITLE
CRAN-ready for 1.0.1

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#341]
- [x] `devtools::spell_check()`
- [x] ~Delete~ Use `@keywords internal` for all man files for unexported functions.
- [x] decide on line break for named arguments (#318).
- [x] Get rid of notes.
- [x] Update NEWS.md. Review PRs messages.
- [x] Wait for new krlmlr/enc release and adapt DESCRIPTION.
- [x] Build vignettes locally.
- [x] update Date: field in DESCRIPTION
- [x] Bump version to 1.0.1.
- [x] run CI on fork lorenzwalthert/cranrel to make sure `R CMD check` reported via `tic / rcmdcheck` packages is identical to `$R CMD check`.
- [x] build with win-build.
- [ ] revdep checking.
- [ ] Update cran-release-notes.md

**Comment by krlmlr** [comment]
I forgot that you don't need to delete `.man` files, you can use the `@noRd` tag instead.

**Comment by lorenzwalthert** [comment]
So should we remove the `.Rd` of all non-exported functions permanently with `@noRd`?

**Comment by krlmlr** [comment]
That sounds like a good idea.

**Comment by lorenzwalthert** [comment]
Not so sure anymore about the `@noRd`solution.

* Exported functions cannot inherit parameters from unexported functions. This triggers a whole chain of problems.
* Having the full documentation version available during development might be helpful exactly because of that. Using `@inheritsParams` makes it difficult to see the whole documentation for a function just from the source code. Hence I would prefer to have the rendered `.Rd` available in some cases.

Can't we just use `@keywords internal` to generate the documentation but not adding it to the index as suggested in the [roxygen vignette](https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html)

**Comment by krlmlr** [comment]
Sure, we could try `@keywords internal`.

**Comment by lorenzwalthert** [comment]
@krlmlr How do we do revdep checking for exampletestr and usethis?

**Comment by krlmlr** [comment]
Perhaps with the revdepcheck package from r-lib? `revdepcheck::revdep_check()` should do the job, there are also some functions that summarize the results.

**Comment by lorenzwalthert** [comment]
Thanks for the hint, just trying that out now.

**Comment by lorenzwalthert** [comment]
Submitted to CRAN.
