### ISSUE TITLE
Prepare release v1.0.2

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#397]
styler needs to be updated on CRAN at least when R 3.6 is rolled out because of #393. It's mainly going to be a maintenance release, see `NEWS.md`. We'd also like to increase the minimal version dependency on `enc` once a fundamental problem with `enc` is resolved (krlmlr/enc#21).

Otherwise, we'd like to postpone any of the open PRs and issues that implement new features to a  subsequent release.

**Comment by lorenzwalthert** [comment]
- [ ] `devtools::spell_check()`
- [ ] Get rid of notes.
- [ ] Update NEWS.md. Review PRs messages.
- [ ] Build vignettes locally.
- [ ] update Date: field in DESCRIPTION
- [ ] Bump version to 1.0.1.
- [ ] run CI on fork lorenzwalthert/cranrel to make sure `R CMD check` reported via `tic / rcmdcheck` packages is identical to `$R CMD check`.
- [ ] build with win-build.
- [ ] revdep checking.
- [ ] Update cran-release-notes.md

**Comment by lorenzwalthert** [comment]
@krlmlr submitted v1.0.2 just now.

**Comment by krlmlr** [comment]
Thanks for your ongoing hard work on the package!
