### ISSUE TITLE
Re-license styler

### ISSUE THREAD

**Issue by hadley** [r-lib/styler#690]
We are systematically re-licensing tidyverse and r-lib packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio [contributors](https://github.com/r-lib/styler/graphs/contributors). @devSJR, @Emiller88, @jonmcalder, @katrinleinweber, @lorenzwalthert, @michaelquinn32, @pat-s, @pratishrai, @renkun-ken, @riccardoporreca, @yutannihilation, would you permit us to re-license styler with the MIT license? If so, please comment "I agree" below.

* [x] [@devSJR](https://github.com/r-lib/styler/commits?author=devSJR)  
* [x] [@Emiller88](https://github.com/r-lib/styler/commits?author=Emiller88)  
* [x] [@jonmcalder](https://github.com/r-lib/styler/commits?author=jonmcalder)  
* [x] [@katrinleinweber](https://github.com/r-lib/styler/commits?author=katrinleinweber)  
* [x] [@lorenzwalthert](https://github.com/r-lib/styler/commits?author=lorenzwalthert)  
* [x] [@michaelquinn32](https://github.com/r-lib/styler/commits?author=michaelquinn32)  
* [x] [@pat-s](https://github.com/r-lib/styler/commits?author=pat-s)  
* [x] [@pratishrai](https://github.com/r-lib/styler/commits?author=pratishrai)  
* [x] [@renkun-ken](https://github.com/r-lib/styler/commits?author=renkun-ken)  
* [x] [@riccardoporreca](https://github.com/r-lib/styler/commits?author=riccardoporreca)  
* [x] [@yutannihilation](https://github.com/r-lib/styler/commits?author=yutannihilation)

**Comment by lorenzwalthert** [comment]
I agree.

**Comment by Emiller88** [comment]
I agree

**Comment by renkun-ken** [comment]
I agree

**Comment by devSJR** [comment]
I agree

On November 1, 2020 6:50:54 PM GMT+01:00, Hadley Wickham <notifications@github.com> wrote:
>We are systematically re-licensing tidyverse and r-lib packages to use
>the MIT license, to make our package licenses as clear and permissive
>as possible. To do so, we need the approval of all copyright holders,
>which I have found by reviewing contributions from all all non-RStudio
>[contributors](https://github.com/r-lib/styler/graphs/contributors).
>@devSJR, @Emiller88, @jonmcalder, @katrinleinweber, @lorenzwalthert,
>@michaelquinn32, @pat-s, @pratishrai, @renkun-ken, @riccardoporreca,
>@yutannihilation, would you permit us to re-license styler with the MIT
>license? If so, please comment "I agree" below.
>
>* [ ] [@devSJR](https://github.com/r-lib/styler/commits?author=devSJR) 
>
>* [ ]
>[@Emiller88](https://github.com/r-lib/styler/commits?author=Emiller88) 
>
>* [ ]
>[@jonmcalder](https://github.com/r-lib/styler/commits?author=jonmcalder)
> 
>* [ ]
>[@katrinleinweber](https://github.com/r-lib/styler/commits?author=katrinleinweber)
> 
>* [ ]
>[@lorenzwalthert](https://github.com/r-lib/styler/commits?author=lorenzwalthert)
> 
>* [ ]
>[@michaelquinn32](https://github.com/r-lib/styler/commits?author=michaelquinn32)
> 
>* [ ] [@pat-s](https://github.com/r-lib/styler/commits?author=pat-s)  
>* [ ]
>[@pratishrai](https://github.com/r-lib/styler/commits?author=pratishrai)
> 
>* [ ]
>[@renkun-ken](https://github.com/r-lib/styler/commits?author=renkun-ken)
> 
>* [ ]
>[@riccardoporreca](https://github.com/r-lib/styler/commits?author=riccardoporreca)
> 
>* [ ]
>[@yutannihilation](https://github.com/r-lib/styler/commits?author=yutannihilation)
> 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/r-lib/styler/issues/690

-- 
Dr. Stefan Rödiger
Group Leader
BTU Cottbus – Senftenberg Campus Senftenberg Institute of Biotechnology 
Universitätsplatz 1 
01968 Senftenberg
Germany 
0049-3573-85936 
Stefan.Roediger@b-tu.de http://www.researchgate.net/profile/Stefan_Roediger/

**Comment by pat-s** [comment]
I agree

**Comment by jonmcalder** [comment]
I agree

**Comment by yutannihilation** [comment]
I agree

**Comment by michaelquinn32** [comment]
I agree.

**Comment by riccardoporreca** [comment]
I agree

**Comment by pratishrai** [comment]
I agree

**Comment by batpigandme** [comment]
Hi, @katrinleinweber,
We'd love to get your agreement please, if you could take a look when you have a chance. 🙂
Thanks!

**Comment by katrinleinweber** [comment]
I agree. Sorry for the delay 😓
